### PR TITLE
Add row_pre_processing-feature at CSV-destination

### PR DESCRIPTION
**Pull request by wuarmin**
Hello @thbar !
I would need that feature. WDYT?
best regards

### CODE REVIEW

**Comment by ttilberg** [comment]
To add support to the general idea (not necessarily the implementation), my own `CSVDestination` also has something similar.

This has been helpful for me when I define multiple destinations, and want to split the records based on whether a row has `:_errors` or not.

At first, I didn't agree with the source also having this, since it duplicates the function of the first transform, but perhaps it could provide the same type of benefit. Can you share a use case where the source having a preprocessor is more valuable than using a transform? Or is it merely for symmetry?

**Comment by wuarmin** [comment]
I don't know what you mean with 'since it duplicates the function of the first transform'. I added the feature to the CSV-destination.

My usecase is the same as yours: Routing to multiple destinations. Furthermore I have usecases, where I want to apply destination-specific transforms at the pre_processor.

**Comment by thbar** [comment]
Hello @wuarmin!

It can be definitely useful for multi-destinations routing (this is what Kiba Pro does for [bulk insert/upsert](https://github.com/thbar/kiba/wiki/SQL-Bulk-Insert-Upsert-Destination)).

That said, I will propose a more general implementation that you can use for any destination.

I will create a separate PR and will request your feedback & testing on this!

**Comment by wuarmin** [comment]
@thbar that sounds great!

**Comment by ttilberg** [comment]
@wuarmin Sorry, you're right. When I was reviewing the changes to the readme from my phone, there were sections related to CSVSource -- but it was only removing spaces at end of lines in the readme. My first glance had me thinking that you were also adding the feature to the source as well. Cheers!

**Comment by wuarmin** [comment]
@ttilberg 😅 that makes sense!

@thbar can you please show (pseudo-code), what you want to propose? Another dsl-element? I.e. route

**Comment by thbar** [comment]
@wuarmin I'm not 100% sure yet, because I don't want to go too far on what could be full routing for now. I will likely take some form of decorator pattern.

I will provide more feedback very soon, working on it!

**Comment by thbar** [comment]
I've implemented the generic version (which I have thought before in the past at various times) in #30.

I've added documentation in the diff itself.

@wuarmin can you try out the `destination-row-pre-processor` branch and see if it works for you? I'll keep #29 opened for the mean time.

**Comment by wuarmin** [comment]
Hello @thbar !
Thank you for your effort. Your implementation works for me:

```ruby
destination Kiba::Common::Destinations::DestinationPreProcessor,
  row_pre_processor: -> (row) {
    row[:_type] == :protocol ? row : nil
  },
  destination: [ Kiba::Common::Destinations::CSV, filename: 'phone6_protocol.csv' ]
```
Can you please explain, why you don't want to support returning N rows?

best regards

**Comment by thbar** [comment]
@wuarmin thanks for your feedback, glad it works for you!

> Can you please explain, why you don't want to support returning N rows?

In general, I'm very conservative before adding anything in Kiba/Common/Pro.

I want long-term maintenance to be sustainable, and also I want to make sure I have sufficient "from-the-field" inputs, based on multiple projects, to figure out how generic/composable components could be (it is so tempting to add project-specific logic), before moving on. The whole thing must remain coherent & move together.

In that respect, I have various prototypes/ideas in mind, some which could cover a part of that scenario, in even more generic fashion (with streams / enumerators etc), so I don't want to add anything not strictly needed at this point.

For now, if you need N rows, I suggest you create a row as an array, then later use the [EnumerableExploder](https://github.com/thbar/kiba-common#kibacommontransformsenumerableexploder) before the destination. Filtering will still be possible.

Question for you @wuarmin: do you have a strong, current need to support returning N rows right now?

**Comment by wuarmin** [comment]
Good morning @thbar !

> In general, I'm very conservative before adding anything in Kiba/Common/Pro.
> 
> I want long-term maintenance to be sustainable, and also I want to make sure I have sufficient "from-the-field" inputs, based on multiple projects, to figure out how generic/composable components could be (it is so tempting to add project-specific logic), before moving on. The whole thing must remain coherent & move together.

I totally agree with you and think this is a smart approach, especially for the long-term vision. I think the single responsible principle is very important. A software brick with many options and many different features is hard to use and to maintain. 

> Question for you @wuarmin: do you have a strong, current need to support returning N rows right now?

Yes I have a usecase, here's a simple example, I couldn't handle with plain old Kiba-Bricks.
```ruby
  def run
    job = Kiba.parse do
      source Kiba::Common::Sources::Enumerable, [
        { name: "world", protocol_rows: [{ status: :ok }, { status: :warning }] },
        { name: "mars", protocol_rows: [{ status: :error }, { status: :ok }] },
      ]

      destination Kiba::Common::Destinations::DestinationPreProcessor,
        row_pre_processor: -> (row) { row.except(:protocol_rows) },
        destination: [ Kiba::Common::Destinations::CSV, filename: 'main.csv' ]

      destination Kiba::Common::Destinations::DestinationPreProcessor,
        row_pre_processor: -> (row) { row.fetch(:protocol_rows) }, # error!
        destination: [ Kiba::Common::Destinations::CSV, filename: 'protocol.csv' ]
    end

    Kiba.run(job)

    puts IO.read('main.csv')
    puts IO.read('protocol.csv')
  end
```
Maybe you have a trick to solve this. If not, what to you think of a new generic destination `Kiba::Common::Destinations::Enumerable`, which uses the decorator-pattern in the same manner as the new `Kiba::Common::Destinations::DestinationPreProcessor`.

best regards

**Comment by thbar** [comment]
Hi @wuarmin! To solve that exact problem without resorting to a 2-pass process (which can also be another solution), there is a trick indeed: you can rely on Ruby's `Enumerator` and Kiba's `EnumerableExploder` like this:

```ruby
job = Kiba.parse do
  source Kiba::Common::Sources::Enumerable, [
    { name: "world", protocol_rows: [{ status: :ok }, { status: :warning }] },
    { name: "mars", protocol_rows: [{ status: :error }, { status: :ok }] },
  ]
  
  transform do |r|
    Enumerator.new do |y|
      # NOTE: you can use Hash#reject from ActiveSupport instead if you prefer here, as you did!
      y << r.reject { |k,_| k == :protocol_rows }
      r.fetch(:protocol_rows).each do |sub_row|
        y << sub_row
      end
    end
  end
  
  transform Kiba::Common::Transforms::EnumerableExploder

  transform { |r| p r }
end
```

In that case the output will be:

```ruby
{:name=>"world"}
{:status=>:ok}
{:status=>:warning}
{:name=>"mars"}
{:status=>:error}
{:status=>:ok}
```

The trick may or may not work, if your actual use-case is slightly different, but in general this is a fairly convenient trick, that you can use in a number of places.

From there, to implement robust routing, you can add a specific field to decide the routing, like:

```ruby
# NOTE: using ActiveSupport Hash#reject for conciseness
Enumerator.new do |y|
  y << r.except(:protocol_rows).merge(type: 0)
  r.fetch(:protocol_rows).each do |sub_row|
    y << sub_row.merge(type: 1)
  end
end
```

and then:

```ruby
destination Kiba::Common::Destinations::DestinationPreProcessor,
  row_pre_processor: -> (row) { row.fetch(:type) == 0 ? row.except(:type) : nil },
  destination: [ Kiba::Common::Destinations::CSV, filename: 'main.csv' ]

destination Kiba::Common::Destinations::DestinationPreProcessor,
  row_pre_processor: -> (row) { row.fetch(:type) == 1 ? row.except(:type) : nil },
  destination: [ Kiba::Common::Destinations::CSV, filename: 'protocol.csv' ]
```

Note that I agree, though, that ultimately an enumerable decorator will be useful, but I want to give me some time on how to add that (most likely, there will be an explicit flag `enumerate: true` to trigger the iteration, otherwise based on experience, the logic to determine what should be enumerated will be error-prone).

Let me know what you think @wuarmin!

**Comment by thbar** [comment]
PS: I only figured out the `Enumerator` trick recently, I will update the documentation here and on the Kiba wiki with references to this later.

**Comment by wuarmin** [comment]
Hi @thbar!

Thank you for this. I think this is a good solution and a wiki update will defenitely help people. I believe this is a common usecase, especially at json-etl's.

best regards

**Comment by thbar** [comment]
@wuarmin perfect, thanks!

I'll close this PR in favour of #30, and have added reminders for the documentation.

Please track #30, I will check out a few things and will prepare a release.

**Comment by wuarmin** [comment]
Great 👍

**Pull request closed without merging**
